### ISSUE TITLE
FaceDetectorPreset values not working. Box mode is only doing a blur instead of bounding box.

### ISSUE THREAD

**Issue by bhsuresh** [Azure-Samples/media-services-v3-dotnet#42] opened 2021-07-19 19:18 UTC
FaceRedactor project:

When we change the properties of FaceDetectorPreset - it's not working. It still uses the default (blur, redact)...

mode: FaceRedactorMode.Analyze
It's not taking Analyze value.

 blurType: BlurType.Box
It's not taking Box value. Looks like it's always blur no matter what we pass.

**Comment by johndeu** [comment] 2021-07-23 17:46
@bhsuresh  I actually did not write the sample to support Analyze (2=pass) mode yet.  
It really only handles the single pass combined mode right now. 

For the blur Type issue, I will take a look at at that myself right now. 

If you want to modify the sample to support two pass Analyze mode... I would suggest copying that folder and creating a 2nd sample that can do the more complex 2-pass mode and contributing it back. 

The issue is, it requires someone to modify the output .json file and then submit it... so it becomes a bigger sample.

**Comment by johndeu** [comment] 2021-07-23 17:48
Also note this in the readme...

> [!NOTE]
> The Sample is only setup to support a single pass redaction using the combined mode. Setting to just "analyze" will result in the output of just the .json file.  If you set the sample to use the "redact" mode you will get a Job error, because the sample is not uploading the output from the required first-pass using the "analyze" mode.  Feel free to modify the sample to upload the output from the "analyze" mode, modify the .json file and play around with the blur settings to get a feel for how the 2-pass operation works.

**Comment by johndeu** [comment] 2021-07-23 17:58
Confirmed the bug!  

I also can't get it to use box mode. Filing this issue on the team. Marking this as Bug here and will keep it open 

     // Create a Face Detector preset and enable redaction/blurring of the faces.
            Preset faceRedactionPreset = new FaceDetectorPreset(
                resolution: AnalysisResolution.SourceResolution,
                mode: FaceRedactorMode.Combined, // Use the Combined mode here. This is the single pass mode where detection and blurring happens as one pass - if you want to analyze and get JSON results first before blur, use Analyze mode, followed by Redact mode. 
                blurType: BlurType.Box // Sets the amount of blur. For debugging purposes you can set this to Box to just see the outlines of the faces.
            );

**Comment by johndeu** [comment] 2021-07-30 21:45
@bhsuresh - actually looking at this again, i dont think it is a bug in the API. 
It appears to be a sample issue.  The Transform name is only used once on creation, and then it is skipped each time you run or change the sample again.  I should change the sample to delete the Transform at the end and clean it up.  Otherwise, the Transform does not pick up the change for the blurType or the mode.  
I updated the cleanup code - which was not even deleting the Transform. (oops sorry!)

**Comment by johndeu** [comment] 2021-07-30 21:46
Run it twice if needed to delete the old Transform, or just change the name of the Transform to create a new one.

**Comment by johndeu** [comment] 2021-07-30 22:09
Closing as this was an issue with the Transform not being deleted in the sample- and not an API issue.

**Closed** 2021-07-30 22:08 UTC
Labels: bug

**Comment by bhsuresh** [comment] 2021-08-11 19:33
Thank you John. I will look into it. Appreciate your help..
